export const categories = [
  { id: 'electronica', name: 'Electrónica', icon: 'smartphone', image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&q=80&w=400' },
  { id: 'hogar', name: 'Hogar', icon: 'home', image: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?auto=format&fit=crop&q=80&w=400' },
  { id: 'moda', name: 'Moda', icon: 'shirt', image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&q=80&w=400' },
  { id: 'fitness', name: 'Fitness', icon: 'dumbbell', image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&q=80&w=400' },
  { id: 'gaming', name: 'Gaming', icon: 'gamepad-2', image: 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&q=80&w=400' }
];

export const products = [
  {
    id: 1,
    name: 'Auriculares Sony WH-1000XM5',
    category: 'electronica',
    price: 349.99,
    oldPrice: 399.99,
    discount: 12,
    rating: 4.8,
    reviews: 1245,
    image: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&q=80&w=800',
    description: 'Auriculares inalámbricos con la mejor cancelación de ruido del mercado. Batería de 30 horas y diseño ultraligero.',
    specs: ['Bluetooth 5.2', 'Cancelación de ruido activa', 'Batería 30h', 'Carga rápida']
  },
  {
    id: 2,
    name: 'MacBook Pro 14" M3',
    category: 'electronica',
    price: 1599.00,
    oldPrice: null,
    discount: null,
    rating: 4.9,
    reviews: 856,
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&q=80&w=800',
    description: 'El portátil más avanzado para profesionales. Chip M3 Pro, pantalla Liquid Retina XDR y hasta 18 horas de batería.',
    specs: ['Chip M3 Pro', '16GB RAM', '512GB SSD', 'Pantalla 14.2" XDR']
  },
  {
    id: 3,
    name: 'Silla Ergonómica Herman Miller Aeron',
    category: 'hogar',
    price: 1200.00,
    oldPrice: 1400.00,
    discount: 14,
    rating: 4.7,
    reviews: 432,
    image: 'https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?auto=format&fit=crop&q=80&w=800',
    description: 'La silla de oficina más icónica y ergonómica del mundo. Diseñada para mantenerte cómodo durante largas jornadas.',
    specs: ['Malla transpirable', 'Soporte lumbar ajustable', 'Garantía 12 años', 'Inclinación sincronizada']
  },
  {
    id: 4,
    name: 'Cafetera Breville Barista Express',
    category: 'hogar',
    price: 699.95,
    oldPrice: null,
    discount: null,
    rating: 4.6,
    reviews: 2100,
    image: 'https://images.unsplash.com/photo-1517246225322-9f94636404d6?auto=format&fit=crop&q=80&w=800',
    description: 'Crea café de especialidad en casa. Molinillo cónico integrado y varilla de vapor para microespuma.',
    specs: ['Molinillo integrado', 'Bomba italiana 15 bares', 'Control de temperatura PID', 'Acero inoxidable']
  },
  {
    id: 5,
    name: 'Zapatillas Nike Air Zoom Pegasus 40',
    category: 'moda',
    price: 129.99,
    oldPrice: 149.99,
    discount: 13,
    rating: 4.5,
    reviews: 3400,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=800',
    description: 'El caballo de batalla con alas. Zapatillas de running reactivas y cómodas para cualquier distancia.',
    specs: ['Amortiguación Zoom Air', 'Malla transpirable', 'Suela de goma duradera', 'Ajuste seguro']
  },
  {
    id: 6,
    name: 'Chaqueta de Cuero Vintage',
    category: 'moda',
    price: 199.00,
    oldPrice: 250.00,
    discount: 20,
    rating: 4.8,
    reviews: 156,
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&q=80&w=800',
    description: 'Chaqueta de cuero genuino estilo motero con acabado vintage. Perfecta para un look casual y atrevido.',
    specs: ['100% Cuero Genuino', 'Forro interior suave', 'Cremalleras YKK', 'Corte ajustado']
  },
  {
    id: 7,
    name: 'Set de Pesas Ajustables Bowflex',
    category: 'fitness',
    price: 399.00,
    oldPrice: 450.00,
    discount: 11,
    rating: 4.7,
    reviews: 890,
    image: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&q=80&w=800',
    description: 'Reemplaza 15 pares de mancuernas con este set ajustable. Cambia el peso fácilmente con un dial.',
    specs: ['Ajustable de 2 a 24 kg', 'Diseño compacto', 'Agarre ergonómico', 'Mecanismo seguro']
  },
  {
    id: 8,
    name: 'Esterilla de Yoga Premium Liforme',
    category: 'fitness',
    price: 140.00,
    oldPrice: null,
    discount: null,
    rating: 4.9,
    reviews: 560,
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&q=80&w=800',
    description: 'La esterilla con mejor agarre del mercado, incluso con sudor. Incluye sistema de alineación patentado.',
    specs: ['Agarre extremo', 'Sistema de alineación', 'Ecológica y biodegradable', 'Más ancha y larga']
  },
  {
    id: 9,
    name: 'Monitor LG UltraGear 27" 144Hz',
    category: 'gaming',
    price: 299.99,
    oldPrice: 349.99,
    discount: 14,
    rating: 4.6,
    reviews: 1120,
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&q=80&w=800',
    description: 'Monitor gaming Nano IPS con tiempo de respuesta de 1ms y tasa de refresco de 144Hz para una fluidez total.',
    specs: ['Resolución 1440p', 'Panel Nano IPS', '144Hz / 1ms', 'G-Sync Compatible']
  },
  {
    id: 10,
    name: 'Teclado Mecánico Keychron Q1',
    category: 'gaming',
    price: 169.00,
    oldPrice: null,
    discount: null,
    rating: 4.8,
    reviews: 450,
    image: 'https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&q=80&w=800',
    description: 'Teclado mecánico custom 75% con cuerpo de aluminio completo. Totalmente personalizable y hot-swappable.',
    specs: ['Cuerpo de aluminio CNC', 'Hot-swappable', 'Compatible Mac/Windows', 'QMK/VIA support']
  },
  {
    id: 11,
    name: 'Smartwatch Garmin Fenix 7',
    category: 'electronica',
    price: 699.99,
    oldPrice: 799.99,
    discount: 12,
    rating: 4.8,
    reviews: 670,
    image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&q=80&w=800',
    description: 'Reloj GPS multideporte premium con carga solar, mapas topográficos y métricas de entrenamiento avanzadas.',
    specs: ['Carga Solar', 'Mapas TopoActive', 'Linterna LED integrada', 'Batería hasta 28 días']
  },
  {
    id: 12,
    name: 'Mochila The North Face Borealis',
    category: 'moda',
    price: 99.00,
    oldPrice: null,
    discount: null,
    rating: 4.7,
    reviews: 2300,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800',
    description: 'Mochila versátil de 28 litros con sistema de suspensión FlexVent para máxima comodidad y soporte.',
    specs: ['Capacidad 28L', 'Funda para portátil 15"', 'Sistema FlexVent', 'Repelente al agua']
  }
];
